### PR TITLE
Fix keybindings gaps keysym

### PR DESCRIPTION
**Pull request by kgilmer**
From slack discussion: https://regolith-linux.slack.com/archives/C03KS5BSF28/p1689954548444809

### CODE REVIEW

**Comment by kgilmer** [comment]
test package build: https://github.com/regolith-linux/voulage/actions/runs/5631854425/job/15259222465

**Review by SoumyaRanjanPatnaik — APPROVED** [review]
Looks good.

**Comment by SoumyaRanjanPatnaik** [comment]
The package declaration for `regolith-sway-gaps` was missing in the control file. Made a commit to add that

**Comment by kgilmer** [comment]
will ship in beta 3

**Pull request merged**
