### PR TITLE
make all non-root config partials soft dependendencies for more flexibility

### PR DESCRIPTION
**Pull request by kgilmer**
This change makes all partials from the root i3/sway config files soft dependencies, meaning they can be uninstalled.  Despite that uninstalling some of these packages without providing a user-based replacement will result in a broken system, IMO the ability for deeper customization is a valid justification.

### CODE REVIEW

**Comment by kgilmer** [comment]
@SoumyaRanjanPatnaik I'm def open to other opinions here if you have them..

**Comment by kgilmer** [comment]
Fixes https://github.com/regolith-linux/regolith-desktop/issues/952 (the reawakening)

**Comment by austinweisgrau** [comment]
The [documentation](https://regolith-desktop.com/docs/using-regolith/configuration/#i3-features) also specifically lists all of these as soft dependencies, and instructs users to uninstall config partials in order to customize them, something that isn't really possible if they are not soft dependencies.

**Comment by SoumyaRanjanPatnaik** [comment]
LGTM.

**Review by SoumyaRanjanPatnaik — APPROVED** [review]

**Pull request merged**
